---
name: tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  tests:
    name: tests 
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.6

    - name: deps
      run: make deps

    - name: test
      run: make test
